#!/usr/bin/env bash
# Build the JPEG XL decode wasm module against a decode-only static build of
# libjxl (v0.11.1). Used for DNG 1.7 raws whose payload is JXL-compressed —
# recent Samsung and Apple phone DNGs — which libraw-wasm cannot decode
# (LibRaw only reaches JXL through the Adobe DNG SDK; see issue #9).
#
# Inputs (fetched/built into this directory; all gitignored):
#   libjxl/            — git clone, tag v0.11.1, with submodules
#   libjxl/build-wasm/ — emcmake build tree (decode libs only)
#   jxl_dec.cpp        — the wrapper (see its header comment)
#
# Outputs, lazy-loaded by src/decode/jxl-worker.js on the first JXL DNG:
#   src/decode/jxl/jxl-module.mjs   — emscripten JS glue. Lives in src/ (not
#     public/) because Vite refuses to import public files as modules.
#   src/decode/jxl/wasm-name.js     — the content-hashed wasm filename, so
#     glue and wasm can never pair up stale across app updates (the wasm is
#     runtime-cached by the service worker, not precached)
#   public/jxl/jxl_dec-<hash>.wasm  — the wasm, fetched at runtime via the
#     glue's locateFile hook (plain static asset, like public/skyseg/)
#
# Requires an activated emsdk (or EMSDK pointing at one) and cmake+ninja
# (pip install --user cmake ninja works fine).
set -euo pipefail
cd "$(dirname "$0")"

if ! command -v em++ >/dev/null 2>&1; then
  EMSDK="${EMSDK:-$HOME/emsdk}"
  # shellcheck disable=SC1091
  source "$EMSDK/emsdk_env.sh"
fi

if [ ! -d libjxl ]; then
  git clone --branch v0.11.1 --depth 1 --recurse-submodules \
    --shallow-submodules https://github.com/libjxl/libjxl.git
fi

if [ ! -f libjxl/build-wasm/lib/libjxl_dec.a ]; then
  # The emsdk 6.0.x clang crashes (segfault) compiling two translation
  # units at high -O on linux/aarch64. Demote them at the CMake level so
  # the workaround survives build.ninja regeneration.
  sed -i 's/COMPILE_OPTIONS "-Wno-psabi"$/COMPILE_OPTIONS "-Wno-psabi;-O0"/' \
    libjxl/third_party/skcms.cmake
  grep -q 'COMPILE_OPTIONS "-O1"' libjxl/lib/jxl_cms.cmake || python3 - <<'EOF'
p = "libjxl/lib/jxl_cms.cmake"
s = open(p).read()
anchor = 'target_compile_options(jxl_cms PRIVATE "${JPEGXL_INTERNAL_FLAGS}")'
add = anchor + '''
# emsdk 6.0.x clang crashes on this TU above -O1 (linux/aarch64)
set_source_files_properties("${CMAKE_CURRENT_SOURCE_DIR}/jxl/cms/jxl_cms.cc"
  PROPERTIES COMPILE_OPTIONS "-O1" TARGET_DIRECTORY jxl_cms)'''
assert anchor in s, "jxl_cms.cmake anchor moved; update build.sh"
open(p, "w").write(s.replace(anchor, add))
EOF

  # Decode-only: no tools/encoder extras, SIMD on.
  emcmake cmake -S libjxl -B libjxl/build-wasm -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=OFF \
    -DBUILD_TESTING=OFF \
    -DJPEGXL_ENABLE_TOOLS=OFF \
    -DJPEGXL_ENABLE_EXAMPLES=OFF \
    -DJPEGXL_ENABLE_MANPAGES=OFF \
    -DJPEGXL_ENABLE_BENCHMARK=OFF \
    -DJPEGXL_ENABLE_DOXYGEN=OFF \
    -DJPEGXL_ENABLE_JNI=OFF \
    -DJPEGXL_ENABLE_SJPEG=OFF \
    -DJPEGXL_ENABLE_OPENEXR=OFF \
    -DJPEGXL_ENABLE_JPEGLI=OFF \
    -DJPEGXL_ENABLE_TRANSCODE_JPEG=OFF \
    -DJPEGXL_ENABLE_SKCMS=ON \
    -DCMAKE_C_FLAGS='-O3 -msimd128' \
    -DCMAKE_CXX_FLAGS='-O3 -msimd128'
  ninja -C libjxl/build-wasm lib/libjxl_dec.a lib/libjxl_cms.a
fi

OUT_MOD=../../src/decode/jxl
OUT_ASSETS=../../public/jxl
mkdir -p "$OUT_MOD" "$OUT_ASSETS"

B=libjxl/build-wasm
em++ -O3 -std=c++17 -msimd128 \
  -I libjxl/lib/include -I "$B/lib/include" \
  jxl_dec.cpp \
  "$B/lib/libjxl_dec.a" "$B/lib/libjxl_cms.a" \
  "$B/third_party/highway/libhwy.a" \
  "$B/third_party/brotli/libbrotlidec.a" \
  "$B/third_party/brotli/libbrotlicommon.a" \
  -o "$OUT_MOD/jxl-module.mjs" \
  -sMODULARIZE=1 -sEXPORT_ES6=1 -sENVIRONMENT=worker \
  -sEXPORTED_FUNCTIONS=_jxl_decode,_jxl_width,_jxl_height,_jxl_channels,_jxl_pixels,_jxl_release,_malloc,_free \
  -sEXPORTED_RUNTIME_METHODS=HEAPU8,HEAPU16 \
  -sALLOW_MEMORY_GROWTH=1 -sINITIAL_MEMORY=64MB \
  -sFILESYSTEM=0 -sASSERTIONS=0

# generated code: keep the typechecker out (eslint ignores the dir too)
sed -i '1i // @ts-nocheck — generated by wasm/jxl/build.sh; do not edit.' \
  "$OUT_MOD/jxl-module.mjs"

# Content-hash the wasm filename and tell the worker about it, so a
# service-worker-cached old wasm can never be paired with new glue.
HASH=$(sha256sum "$OUT_MOD/jxl-module.wasm" | cut -c1-8)
rm -f "$OUT_ASSETS"/jxl_dec-*.wasm
mv "$OUT_MOD/jxl-module.wasm" "$OUT_ASSETS/jxl_dec-$HASH.wasm"
cat > "$OUT_MOD/wasm-name.js" <<EOF
// Generated by wasm/jxl/build.sh; do not edit.
export default "jxl_dec-$HASH.wasm";
EOF

ls -la "$OUT_MOD" "$OUT_ASSETS"
