#!/usr/bin/env bash
# Build the sky-segmentation wasm module against ncnn's prebuilt
# WebAssembly static library (simd, single-threaded — the app cannot
# assume cross-origin isolation for third-party contexts, and one thread
# is plenty for a one-shot 384×384 inference).
#
# Inputs (this directory):
#   skyseg.cpp                        — the glue (see its header comment)
#   ncnn-20260526-webassembly/simd/   — from the ncnn release zip
#   model/skysegsmall_sim-opt-fp16.*  — the 2.2MB U²-NetP sky model
#
# Outputs, lazy-loaded by src/tone/sky-worker.js on the first "+ Sky":
#   src/tone/skyseg/skyseg-module.mjs — emscripten JS glue. Lives in src/
#     (not public/) because Vite refuses to import public files as modules;
#     the worker imports it and Vite bundles it like any source file.
#   public/skyseg/skyseg.wasm         — the wasm, fetched at runtime via the
#     glue's locateFile hook (plain static asset, kept out of the precache)
#   public/skyseg/skyseg.param + .bin — the model, renamed
#
# Requires an activated emsdk (or EMSDK pointing at one).
set -euo pipefail
cd "$(dirname "$0")"

if ! command -v em++ >/dev/null 2>&1; then
  EMSDK="${EMSDK:-$HOME/emsdk}"
  # shellcheck disable=SC1091
  source "$EMSDK/emsdk_env.sh"
fi

NCNN=ncnn-20260526-webassembly/simd
OUT_MOD=../../src/tone/skyseg
OUT_ASSETS=../../public/skyseg
mkdir -p "$OUT_MOD" "$OUT_ASSETS"

# -msimd128 matches the simd variant of the prebuilt lib (wasm-ld refuses
# mixed feature sets). The prebuilt lib is compiled WITH exceptions
# (references __cxa_throw), so exception support must stay enabled here.
em++ -O3 -std=c++11 -msimd128 \
  -I"$NCNN/include/ncnn" \
  skyseg.cpp "$NCNN/lib/libncnn.a" \
  -o "$OUT_MOD/skyseg-module.mjs" \
  -sMODULARIZE=1 -sEXPORT_ES6=1 -sENVIRONMENT=worker \
  -sEXPORTED_FUNCTIONS=_skyseg_load,_skyseg_run,_malloc,_free \
  -sEXPORTED_RUNTIME_METHODS=HEAPU8,HEAPF32 \
  -sALLOW_MEMORY_GROWTH=1 -sINITIAL_MEMORY=64MB \
  -sFILESYSTEM=0 -sASSERTIONS=0

# generated code: keep the typechecker out (eslint ignores the dir too)
sed -i '1i // @ts-nocheck — generated by wasm/skyseg/build.sh; do not edit.' \
  "$OUT_MOD/skyseg-module.mjs"
mv "$OUT_MOD/skyseg-module.wasm" "$OUT_ASSETS/skyseg.wasm"
cp model/skysegsmall_sim-opt-fp16.param "$OUT_ASSETS/skyseg.param"
cp model/skysegsmall_sim-opt-fp16.bin "$OUT_ASSETS/skyseg.bin"

ls -la "$OUT_MOD" "$OUT_ASSETS"
